# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/guede/Downloads/contador_pessoas/contador_pessoas.cache/wt [current_project]
set_property parent.project_path C:/Users/guede/Downloads/contador_pessoas/contador_pessoas.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/guede/Downloads/contador_pessoas/contador_pessoas.srcs/sources_1/new/contador_pessoas.vhd
synth_design -top contador_pessoas -part xc7a100tcsg324-1
write_checkpoint -noxdef contador_pessoas.dcp
catch { report_utilization -file contador_pessoas_utilization_synth.rpt -pb contador_pessoas_utilization_synth.pb }
